name: parla
adopt-info: parla
base: core26
confinement: strict
grade: stable
compression: lzo
platforms:
  amd64:
    build-on: [amd64]
    build-for: amd64
  arm64:
    build-on: [arm64]
    build-for: arm64
  riscv64:
    build-on: [riscv64]
    build-for: riscv64
  ppc64el:
    build-on: [ppc64el]
    build-for: ppc64el
apps:
  parla:
    extensions: [gnome]
    command: usr/bin/parla
    desktop: usr/share/applications/io.github.trufae.Parla.desktop
    common-id: io.github.trufae.Parla
    plugs:
      - network
      - network-status
slots:
  parla:
    interface: dbus
    bus: session
    name: io.github.trufae.Parla
parts:
  parla:
    source: https://github.com/trufae/parla.git
    source-tag: "0.5.8"
    source-type: git
    plugin: meson
    meson-parameters:
      - --prefix=/usr
    parse-info: [usr/share/metainfo/io.github.trufae.Parla.metainfo.xml]
  deltachat-rpc-server:
    plugin: nil
    build-packages:
      - cargo
    build-environment:
      - DELTACHAT_VERSION: "2.53.0"
    override-build: |
      cargo install \
        --profile release \
        --root "${CRAFT_PART_INSTALL}/usr" \
        --git https://github.com/chatmail/core.git \
        --tag "v${DELTACHAT_VERSION}" \
        deltachat-rpc-server
